# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1279, 837)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tenantGetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.tenantGetBtn.setGeometry(QtCore.QRect(1010, 20, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tenantGetBtn.setFont(font)
        self.tenantGetBtn.setObjectName("tenantGetBtn")
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(1010, 120, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName("addBtn")
        self.delBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delBtn.setGeometry(QtCore.QRect(1010, 170, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.delBtn.setFont(font)
        self.delBtn.setObjectName("delBtn")
        self.tenantSavBtn = QtWidgets.QPushButton(self.centralwidget)
        self.tenantSavBtn.setGeometry(QtCore.QRect(1010, 70, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tenantSavBtn.setFont(font)
        self.tenantSavBtn.setObjectName("tenantSavBtn")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(20, 20, 971, 761))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1279, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tenantGetBtn.setText(_translate("MainWindow", "Получить арендаторов"))
        self.addBtn.setText(_translate("MainWindow", "Добавить"))
        self.delBtn.setText(_translate("MainWindow", "Удалить"))
        self.tenantSavBtn.setText(_translate("MainWindow", "Сохранить арендаторов"))
