# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1279, 837)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tenantGetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.tenantGetBtn.setGeometry(QtCore.QRect(1010, 20, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tenantGetBtn.setFont(font)
        self.tenantGetBtn.setObjectName("tenantGetBtn")
        self.tenantAddBtn = QtWidgets.QPushButton(self.centralwidget)
        self.tenantAddBtn.setGeometry(QtCore.QRect(1010, 60, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tenantAddBtn.setFont(font)
        self.tenantAddBtn.setObjectName("tenantAddBtn")
        self.tenantDelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.tenantDelBtn.setGeometry(QtCore.QRect(1100, 60, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tenantDelBtn.setFont(font)
        self.tenantDelBtn.setObjectName("tenantDelBtn")
        self.tenantSavBtn = QtWidgets.QPushButton(self.centralwidget)
        self.tenantSavBtn.setGeometry(QtCore.QRect(1190, 60, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tenantSavBtn.setFont(font)
        self.tenantSavBtn.setObjectName("tenantSavBtn")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(20, 20, 971, 761))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.landlordGetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.landlordGetBtn.setGeometry(QtCore.QRect(1010, 120, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.landlordGetBtn.setFont(font)
        self.landlordGetBtn.setObjectName("landlordGetBtn")
        self.landlordSavBtn = QtWidgets.QPushButton(self.centralwidget)
        self.landlordSavBtn.setGeometry(QtCore.QRect(1190, 160, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.landlordSavBtn.setFont(font)
        self.landlordSavBtn.setObjectName("landlordSavBtn")
        self.landlordDelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.landlordDelBtn.setGeometry(QtCore.QRect(1100, 160, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.landlordDelBtn.setFont(font)
        self.landlordDelBtn.setObjectName("landlordDelBtn")
        self.landlordAddBtn = QtWidgets.QPushButton(self.centralwidget)
        self.landlordAddBtn.setGeometry(QtCore.QRect(1010, 160, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.landlordAddBtn.setFont(font)
        self.landlordAddBtn.setObjectName("landlordAddBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1279, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tenantGetBtn.setText(_translate("MainWindow", "Получить арендаторов"))
        self.tenantAddBtn.setText(_translate("MainWindow", "Добавить"))
        self.tenantDelBtn.setText(_translate("MainWindow", "Удалить"))
        self.tenantSavBtn.setText(_translate("MainWindow", "Сохранить"))
        self.landlordGetBtn.setText(_translate("MainWindow", "Получить арендодателей"))
        self.landlordSavBtn.setText(_translate("MainWindow", "Сохранить"))
        self.landlordDelBtn.setText(_translate("MainWindow", "Удалить"))
        self.landlordAddBtn.setText(_translate("MainWindow", "Добавить"))
